
# 查询最近多少小时的订单
OrderHour: 24

# 提现最多读取页数
WithdrawMaxPage: 1
# 提现最多天数
WithdrawMaxDay: 3

# 充值最多读取页数
RechargeMaxPage: 3
# 充值最多天数
RechargeMaxDay: 3

# 游戏记录最多读取页数
GameLogMaxPage: 3
# 游戏记录最多小时
GameLogMaxHour: 36

# 最大锁定单数
OrderMaxLock: 3

# 处理金额范围
AmountRang: [100,2000]

# 审核配置文件
ReviewFile: review.yaml

# Chrome
Headless: false

